version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:db/development.sqlite3
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    stdin_open: true
    tty: true

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: npm run server
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
  node_modules:
